### ISSUE TITLE
Example of a Query where Variables are Passed

### ISSUE THREAD

**Issue by sheprdinc** [apollographql/frontpage-react-native-app#2]
Also would greatly appreciate an example where the same component has both Read and Write operations.

**Comment by helfer** [comment]
Hey @sheprdinc. Since this is a super minimal example app I don't think it makes sense to include that here. However, the way to pass variables and do mutations is the same with Apollo regardless of whether you're using react or react native, so you can just check the GitHunt-React example app for that!
